version: "3.5"

services:
  e4l-frontend-prod:
    restart: always
    image: ${FRONTEND_IMAGE}:release
    container_name: e4l-frontend-prod
    ports:
      - 8082:80
    volumes:
      - /opt/e4l-news:/usr/share/nginx/news
    environment:
      - PUBLIC_PATH=/
      - API_URL=/API_URL
      - TZ=Europe/Luxembourg
    networks:
      - e4l-db-net

networks:
  e4l-db-net:
    external: true
    name: e4l-db-net
