version: "3.5"

services:
  e4l-backend:
    restart: always
    image: ${BACKEND_IMAGE}:latest
    container_name: e4l-backend
    ports:
      - "8084:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://e4l-db:3306/e4l
      - SPRING_DATASOURCE_USERNAME=e4l
      - SPRING_DATASOURCE_PASSWORD=e4lpassword
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.mariadb.jdbc.Driver
      - DEV_RESOURCES_STATIC_URL=http://192.168.56.11:8082
      - JWT_SECRET=mySecretKey123456789012345678901234567890
      - SIGNATURE_KEY=mySignatureKey12345678901234567890123456
      - ADMIN_EMAIL=admin@e4l.lu
      - ADMIN_PASSWORD=admin123
      - TZ=Europe/Luxembourg
    networks:
      - e4l-db-net

networks:
  e4l-db-net:
    external: true
    name: e4l-db-net
